namespace DTAClient.Online;

/// <summary>
/// The type of a CnCNet IRC network message.
/// </summary>
public enum QueuedMessageType
{
    UNDEFINED,
    CHATMESSAGE,
    SYSTEMMESSAGE,
    GAMESETTINGSMESSAGE,
    GAMEPLAYERSMESSAGE,
    GAMEPLAYERSREADYSTATUSMESSAGE,
    GAMELOCKEDMESSAGE,
    GAMEGETREADYMESSAGE,
    GAMENOTIFICATIONMESSAGE,
    GAMEHOSTINGMESSAGE,
    GAMECHEATERMESSAGE,
    GAMEBROADCASTINGMESSAGE,
    WHOISMESSAGE,
    INSTANTMESSAGE,
    GAMEPLAYERSEXTRAMESSAGE,
}