using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClientCore;
using ClientCore.Extensions;
using ClientGUI;
using DTAClient.Domain;
using Localization;
using Microsoft.Extensions.Logging;
using Microsoft.Xna.Framework;
using Rampastring.Tools;
using Rampastring.XNAUI;
using Rampastring.XNAUI.XNAControls;

namespace DTAClient.DXGUI.Generic
{
    /// <summary>
    /// A window for loading saved singleplayer games.
    /// </summary>
    internal sealed class GameLoadingWindow : XNAWindow
    {
        private readonly GameProcessLogic gameProcessLogic;
        private readonly UserINISettings userIniSettings;
        private readonly XNAMessageBox xnaMessageBox;

        public GameLoadingWindow(WindowManager windowManager, DiscordHandler discordHandler, ILogger logger, GameProcessLogic gameProcessLogic, UserINISettings userIniSettings, XNAMessageBox xnaMessageBox, IServiceProvider serviceProvider)
            : base(windowManager, logger, serviceProvider)
        {
            this.discordHandler = discordHandler;
            this.gameProcessLogic = gameProcessLogic;
            this.userIniSettings = userIniSettings;
            this.xnaMessageBox = xnaMessageBox;
        }

        private DiscordHandler discordHandler;

        private XNAMultiColumnListBox lbSaveGameList;
        private XNAClientButton btnLaunch;
        private XNAClientButton btnDelete;
        private XNAClientButton btnCancel;

        private List<SavedGame> savedGames = new List<SavedGame>();

        public override void Initialize()
        {
            Name = "GameLoadingWindow";
            BackgroundTexture = AssetLoader.LoadTexture("loadmissionbg.png");

            ClientRectangle = new Rectangle(0, 0, 600, 380);
            CenterOnParent();

            lbSaveGameList = new XNAMultiColumnListBox(WindowManager);
            lbSaveGameList.Name = nameof(lbSaveGameList);
            lbSaveGameList.ClientRectangle = new Rectangle(13, 13, 574, 317);
            lbSaveGameList.AddColumn("SAVED GAME NAME".L10N("UI:Main:SavedGameNameColumnHeader"), 400);
            lbSaveGameList.AddColumn("DATE / TIME".L10N("UI:Main:SavedGameDateTimeColumnHeader"), 174);
            lbSaveGameList.BackgroundTexture = AssetLoader.CreateTexture(new Color(0, 0, 0, 128), 1, 1);
            lbSaveGameList.PanelBackgroundDrawMode = PanelBackgroundImageDrawMode.STRETCHED;
            lbSaveGameList.SelectedIndexChanged += ListBox_SelectedIndexChanged;
            lbSaveGameList.AllowKeyboardInput = true;

            btnLaunch = new XNAClientButton(WindowManager);
            btnLaunch.Name = nameof(btnLaunch);
            btnLaunch.ClientRectangle = new Rectangle(125, 345, 110, 23);
            btnLaunch.Text = "Load".L10N("UI:Main:ButtonLoad");
            btnLaunch.AllowClick = false;
            btnLaunch.LeftClick += (_, _) => BtnLaunch_LeftClickAsync().HandleTask();

            btnDelete = new XNAClientButton(WindowManager);
            btnDelete.Name = nameof(btnDelete);
            btnDelete.ClientRectangle = new Rectangle(btnLaunch.Right + 10, btnLaunch.Y, 110, 23);
            btnDelete.Text = "Delete".L10N("UI:Main:ButtonDelete");
            btnDelete.AllowClick = false;
            btnDelete.LeftClick += BtnDelete_LeftClick;

            btnCancel = new XNAClientButton(WindowManager);
            btnCancel.Name = nameof(btnCancel);
            btnCancel.ClientRectangle = new Rectangle(btnDelete.Right + 10, btnLaunch.Y, 110, 23);
            btnCancel.Text = "Cancel".L10N("UI:Main:ButtonCancel");
            btnCancel.LeftClick += BtnCancel_LeftClick;

            AddChild(lbSaveGameList);
            AddChild(btnLaunch);
            AddChild(btnDelete);
            AddChild(btnCancel);

            base.Initialize();

            ListSaves();
        }

        private void ListBox_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (lbSaveGameList.SelectedIndex == -1)
            {
                btnLaunch.AllowClick = false;
                btnDelete.AllowClick = false;
            }
            else
            {
                btnLaunch.AllowClick = true;
                btnDelete.AllowClick = true;
            }
        }

        private void BtnCancel_LeftClick(object sender, EventArgs e)
        {
            Enabled = false;
        }

        private async ValueTask BtnLaunch_LeftClickAsync()
        {
            SavedGame sg = savedGames[lbSaveGameList.SelectedIndex];
            logger.LogInformation("Loading saved game " + sg.FileName);

            FileInfo spawnerSettingsFile = SafePath.GetFile(ProgramConstants.GamePath, ProgramConstants.SPAWNER_SETTINGS);

            if (spawnerSettingsFile.Exists)
                spawnerSettingsFile.Delete();

            await using var spawnStreamWriter = new StreamWriter(spawnerSettingsFile.FullName);
            await spawnStreamWriter.WriteLineAsync("; generated by DTA Client");
            await spawnStreamWriter.WriteLineAsync("[Settings]");
            await spawnStreamWriter.WriteLineAsync($"Scenario={ProgramConstants.SPAWNMAP_INI}");
            await spawnStreamWriter.WriteLineAsync("SaveGameName=" + sg.FileName);
            await spawnStreamWriter.WriteLineAsync("LoadSaveGame=Yes");
            await spawnStreamWriter.WriteLineAsync("SidebarHack=" + ClientConfiguration.Instance.SidebarHack);

            int resHeight = userIniSettings.IngameScreenHeight;

            await spawnStreamWriter.WriteLineAsync("CustomLoadScreen=" + LoadingScreenController.GetLoadScreenName("g", resHeight));
            await spawnStreamWriter.WriteLineAsync("Firestorm=No");
            await spawnStreamWriter.WriteLineAsync("GameSpeed=" + userIniSettings.GameSpeed);
            await spawnStreamWriter.WriteLineAsync();

            FileInfo spawnMapIniFile = SafePath.GetFile(ProgramConstants.GamePath, ProgramConstants.SPAWNMAP_INI);

            if (spawnMapIniFile.Exists)
                spawnMapIniFile.Delete();

            await using var spawnMapStreamWriter = new StreamWriter(spawnMapIniFile.FullName);
            await spawnMapStreamWriter.WriteLineAsync("[Map]");
            await spawnMapStreamWriter.WriteLineAsync("Size=0,0,50,50");
            await spawnMapStreamWriter.WriteLineAsync("LocalSize=0,0,50,50");
            await spawnMapStreamWriter.WriteLineAsync();

            discordHandler.UpdatePresence(sg.GUIName, true);

            Enabled = false;
            gameProcessLogic.GameProcessExited += GameProcessExited_Callback;

            await gameProcessLogic.StartGameProcessAsync();
        }

        private void BtnDelete_LeftClick(object sender, EventArgs e)
        {
            SavedGame sg = savedGames[lbSaveGameList.SelectedIndex];

            xnaMessageBox.Caption = "Delete Confirmation".L10N("UI:Main:DeleteConfirmationTitle");
            xnaMessageBox.Description = string.Format("The following saved game will be deleted permanently:" + Environment.NewLine +
                    Environment.NewLine +
                    "Filename: {0}" + Environment.NewLine +
                    "Saved game name: {1}" + Environment.NewLine +
                    "Date and time: {2}" + Environment.NewLine +
                    Environment.NewLine +
                    "Are you sure you want to proceed?".L10N("UI:Main:DeleteConfirmationText"),
                    sg.FileName, Renderer.GetSafeString(sg.GUIName, lbSaveGameList.FontIndex), sg.LastModified.ToString());
            xnaMessageBox.MessageBoxButtons = XNAMessageBoxButtons.YesNo;
            xnaMessageBox.YesClickedAction = DeleteMsgBox_YesClicked;

            xnaMessageBox.Show();
        }

        private void DeleteMsgBox_YesClicked(XNAMessageBox obj)
        {
            SavedGame sg = savedGames[lbSaveGameList.SelectedIndex];

            logger.LogInformation("Deleting saved game " + sg.FileName);
            SafePath.DeleteFileIfExists(ProgramConstants.GamePath, ProgramConstants.SAVED_GAMES_DIRECTORY, sg.FileName);
            ListSaves();
        }

        private void GameProcessExited_Callback()
        {
            WindowManager.AddCallback(GameProcessExited);
        }

        private void GameProcessExited()
        {
            gameProcessLogic.GameProcessExited -= GameProcessExited_Callback;
            discordHandler.UpdatePresence();
        }

        public void ListSaves()
        {
            savedGames.Clear();
            lbSaveGameList.ClearItems();
            lbSaveGameList.SelectedIndex = -1;

            DirectoryInfo savedGamesDirectoryInfo = SafePath.GetDirectory(ProgramConstants.GamePath, ProgramConstants.SAVED_GAMES_DIRECTORY);

            if (!savedGamesDirectoryInfo.Exists)
            {
                logger.LogInformation("Saved Games directory not found!");
                return;
            }

            IEnumerable<FileInfo> files = savedGamesDirectoryInfo.EnumerateFiles("*.SAV", SearchOption.TopDirectoryOnly);

            foreach (FileInfo file in files)
            {
                ParseSaveGame(file.FullName);
            }

            savedGames = savedGames.OrderBy(sg => sg.LastModified.Ticks).ToList();
            savedGames.Reverse();

            foreach (SavedGame sg in savedGames)
            {
                string[] item = new string[] {
                    Renderer.GetSafeString(sg.GUIName, lbSaveGameList.FontIndex),
                    sg.LastModified.ToString() };
                lbSaveGameList.AddItem(item, true);
            }
        }

        private void ParseSaveGame(string fileName)
        {
            string shortName = Path.GetFileName(fileName);
            var sg = new SavedGame { FileName = shortName };

            try
            {
                sg.ParseInfo();
            }
            catch (Exception ex)
            {
                logger.LogExceptionDetails(ex, "An error occurred while parsing saved game " + shortName);
                return;
            }

            savedGames.Add(sg);
        }
    }
}