name: build client

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  calculate-version:
    name: Calculate Version
    runs-on: windows-latest
    outputs:
      AssemblySemVer: ${{ steps.gitversion.outputs.AssemblySemVer }}
      AssemblySemFileVer: ${{ steps.gitversion.outputs.AssemblySemFileVer }}
      InformationalVersion: ${{ steps.gitversion.outputs.InformationalVersion }}
      SemVer: ${{ steps.gitversion.outputs.SemVer }}
      PreReleaseTag: ${{ steps.gitversion.outputs.PreReleaseTag }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@main
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@main
  publish:
    runs-on: windows-latest
    needs: calculate-version
    env:
      AssemblySemVer: ${{ needs.calculate-version.outputs.AssemblySemVer }}
      AssemblySemFileVer: ${{ needs.calculate-version.outputs.AssemblySemFileVer }}
      InformationalVersion: ${{ needs.calculate-version.outputs.InformationalVersion }}
      SemVer: ${{ needs.calculate-version.outputs.SemVer }}
    strategy:
      matrix:
        game: [Ares,TS,YR]
        framework: [net8.0, net7.0]

    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '8.x.x'

    - name: Build ${{matrix.game}}
      run: ./BuildScripts/Build-${{matrix.game}}.ps1 Release ${{matrix.framework}}
      shell: pwsh

    - uses: actions/upload-artifact@main
      name: Upload Artifacts
      with:
        name: artifacts-${{matrix.game}}-${{matrix.framework}}
        path: ./Compiled/${{matrix.game}}/${{matrix.framework}}
        if-no-files-found: error
  release:
    needs: [calculate-version, publish]
    env:
      PreReleaseTag: ${{ needs.calculate-version.outputs.PreReleaseTag }}
      SemVer: ${{ needs.calculate-version.outputs.SemVer }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Download Artifacts
        uses: actions/download-artifact@main
        with:
          path: ./artifacts
      - name: Prerelease
        if: ${{ env.PreReleaseTag != '' }}
        run: gh release create ${{ format('v{0}', env.SemVer) }} (get-item ./artifacts/*/*.zip) --generate-notes --target ${{ github.sha }} --prerelease
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Release
        if: ${{ env.PreReleaseTag == '' }}
        run: gh release create ${{ format('v{0}', env.SemVer) }} (get-item ./artifacts/*/*.zip) --generate-notes --target ${{ github.sha }}
        env:
          GH_TOKEN: ${{ github.token }}