name: build client

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:
jobs:
  build-clients:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '6.x.x'

    - name: Build All
      run: ./BuildScripts/build-All.ps1
      shell: pwsh

    - uses: actions/upload-artifact@main
      name: Upload Artifacts
      with:
        name: artifacts
        path: ./Compiled