name: build client

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:
jobs:
  build-clients:
    runs-on: windows-2022
    strategy:
      matrix:
        game: [Ares,TS,YR]
        framework: [net8.0, net7.0]

    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '8.x.x'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@main
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@main

    - name: Build ${{matrix.game}}
      run: ./BuildScripts/Build-${{matrix.game}}.ps1 Release ${{matrix.framework}}
      shell: pwsh

    - uses: actions/upload-artifact@main
      name: Upload Artifacts
      with:
        name: artifacts-${{matrix.game}}-${{matrix.framework}}
        path: ./Compiled/${{matrix.game}}/${{matrix.framework}}